### ISSUE TITLE
Training process was stuck when setting resolution to 192x640

### ISSUE THREAD

**Issue by ruili3** [nianticlabs/wavelet-monodepth#5]
Hi,

Here comes a new problem. 
When I trained the model with the resolution of 192*640 with command
`train.py --data_path <path> --log_dir <path> --encoder_type resnet --num_layers 50 --width 640 --height 192 --frame_ids 0 --use_stereo --split eigen_full --num_epochs 30 --use_depth_hints --depth_hint_path <path> --use_wavelets`
, the training process was stuck. The logging message of the first epoch did not show. There was no other message nor error reported. It's pretty weird because the resolution is not supposed to interfere with the training process. Can you please help to debug that? Thank you!

**Comment by ruili3** [comment]
It is caused by cv2.resize() in the [dataset](https://github.com/nianticlabs/wavelet-monodepth/blob/1d9f945d766a449b966179915deb0c92dc595d27/KITTI/datasets/mono_dataset.py#L259) that results in deadlock in the system.

Adding `cv2.setNumThreads(0)` aftering importing the `cv2` lib will help to solve it.

**Comment by MichaelRamamonjisoa** [comment]
Hi, 

Sorry for getting back to you so late. I'm glad you found the solution. It is also used in [Depth Hints](https://github.com/nianticlabs/depth-hints/blob/aa2ecf7bc88ef2edbd434fbf064ac024cec8e85d/datasets/mono_dataset.py#L20) and should have be kept.

Fixed it in ac143e3d64757b5cc14ea783e2552e4ceb14287b, thanks!
