### ISSUE TITLE
about the function of coefficients , e.g. (2 ** 3)(2 ** 2)(2 ** 1) 

### ISSUE THREAD

**Issue by c-yn** [nianticlabs/wavelet-monodepth#7]
Hello, what is the function of 2 **2 when obtaining 'h' 
 > h = (2 ** 2) * self.wave1(x_d1).unsqueeze(1)

and other examples, including
ll = (2 ** 3) * self.wave1_ll(x_d1)
h = (2 ** 1) * self.wave2(x_d2).unsqueeze(1)

Could you please tell the function of that? Thank you in advance.

**Comment by MichaelRamamonjisoa** [comment]
Hi,

Thanks for your interest in WaveletMonodepth!

As explained in the following comment https://github.com/nianticlabs/wavelet-monodepth/issues/4#issuecomment-907153543, those coefficients are used to scale between the wavelet coefficient's range such that they are compatible with their level (in the wavelet decomposition). 

Inverse and direct wavelet transforms scale (down and up respectively) the range of their input by a factor of two.
